version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./compose/conf/mosquitto:/mosquitto/config
      - ./compose/data/mosquitto:/mosquitto/data
      - ./compose/log/mosquitto:/mosquitto/log
    networks:
      - home
    ports:
      - "1883:1883"
      - "8883:8883"


networks:
  home:
